# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 519a05d4a937efb6d22299b90ba12555be14987dafb799021460fe6c62ab974dcee7b504a2afbc389378ae7e31ce6be865ceb1cc352c55659b63272d6e89d8ba

test:
  secret_key_base: a99009150e4edae21b4780a150f9d37e7865fa743af09c31eea5ceb7657108a5fc85ab333bc74f72bf31e8da5edcfcb3eebd7b80bb1440ab29e155b617e7e268

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
